### PR TITLE
dark mode feature added

### PR DESCRIPTION
**Pull request by yube01**
Dark mode feature added
#5

### CODE REVIEW

**Comment by yube01** [comment]
@Aloneking789 I have created a PR

**Review by ag21o9 — CHANGES_REQUESTED** [review]
In Dark Mode, try to make the navbar and the home section more distinct, as the navbar is not visible or clearly separated. Additionally, horizontal rulers are hidden.

**Comment by yube01** [comment]
@ag21o9 I have fixed the issue

**Review by ag21o9 — CHANGES_REQUESTED** [review]
Try to make all Horizontal rulers white during dark mode, it is still looking combined
And try to beautify the dark mode button with switch button

**Comment by yube01** [comment]
@ag21o9 Horizontal rulers white during dark mode fixed

**Comment by yube01** [comment]
@ag21o9  the dark mode button with switch button added

**Review by ag21o9 — APPROVED** [review]
Edit Home page of the portflio with vision and motto section and also a beautiful footer

**Pull request merged**
